### ISSUE TITLE
Support for ISODate format

### ISSUE THREAD

**Issue by Delimer** [SamuelTS/MongoDB-PHP-GUI#1]
in mongo console I see
`"createdAt" : ISODate("2020-08-11T09:06:32.802Z")`

but in interface I see
`createdAt{1}
$date{1}
$numberLong:1597136792802`

and date in this format hard to edit

**Comment by SamuelTS** [comment]
Thanks @Delimer. I'll try to fix that.

**Comment by SamuelTS** [comment]
Since v1.0.3 of MongoDB PHP GUI, ISODate format is supported. Please upgrade your version, then if you still experience any problem: feel free to reopen an issue.
