### ISSUE TITLE
Publish image to Docker hub

### ISSUE THREAD

**Issue by bigwheels16** [SamuelTS/MongoDB-PHP-GUI#10]
Would you consider publishing the Docker image to Docker hub?  You can do it for free using the Dockerhub free plan which already integrates with Github.

**Comment by SamuelTS** [comment]
Yes.

**Comment by creharmony** [comment]
My 2 cents / after [a little search](https://hub.docker.com/search?q=MongoDB-PHP-GUI&type=image), I try the [first one](https://hub.docker.com/r/patrickdk/mongodb-php-gui) with success.

**Comment by SamuelTS** [comment]
> My 2 cents : after [a little search](https://hub.docker.com/search?q=MongoDB-PHP-GUI&type=image), I tried the [first one](https://hub.docker.com/r/patrickdk/mongodb-php-gui) with success.

Thanks for the information @creharmony.

**Comment by SamuelTS** [comment]
I've published [MongoDB PHP GUI](https://hub.docker.com/r/samueltallet/mongodb-php-gui) to Docker Hub.
