### ISSUE TITLE
Shared hosting

### ISSUE THREAD

**Issue by ririko5834** [SamuelTS/MongoDB-PHP-GUI#12]
Is this hostable on shared hosting without access to the cmd line?

**Comment by SamuelTS** [comment]
It really depends on hosting offer... Usually, a dedicated hosting is required.

**Comment by SamuelTS** [comment]
Since this GUI is now available at [Docker Hub](https://hub.docker.com/r/samueltallet/mongodb-php-gui), maybe you'll get more lucks to deploy it on a shared hosting.
