### ISSUE TITLE
Bad redirect - Weird layout

### ISSUE THREAD

**Issue by Ipmake123** [SamuelTS/MongoDB-PHP-GUI#13]
I just finished setting up the gui on Ubuntu 20.10 using the apache 2 method. But my site looks like this weirdly: 
![grafik](https://user-images.githubusercontent.com/60793254/117425395-09ea5380-af23-11eb-8093-f69a2407ad45.png)

Please help me

**Comment by SamuelTS** [comment]
How looks URL? Are there errors in browser console?

**Comment by thanhdiepts** [comment]
I had the same issue:
`http://[domain]//index/login`
I tried to remove /index part then it works properly,

**Comment by SamuelTS** [comment]
I've released a fix a few minutes ago... Please upgrade to [latest version](https://github.com/SamuelTS/MongoDB-PHP-GUI/releases), then tell me if it helps.

**Comment by SamuelTS** [comment]
If issue persists after upgrade: post a comment.
