### ISSUE TITLE
Query database: key shortcuts for find/count

### ISSUE THREAD

**Issue by creharmony** [SamuelTS/MongoDB-PHP-GUI#17]
I would like a way to execute a find/count without leaving text area. 
- key shortcuts could be fine for that.
- need to focus automatically on text area on fresh result

**Comment by SamuelTS** [comment]
Thanks for the idea!

**Comment by creharmony** [comment]
Hey cool ! I try latest version, and my feedback:
- I searched a little the current version of app and then found that it's in the title 👍 
- docker hub image has not been updated sing 5 month so I decided to clone/build it localy (with [this fix for dns](https://stackoverflow.com/questions/66042756/apk-return-dns-lookup-error-on-docker-build/69651640#69651640)) : `docker build --network=host -t mongodb-php-gui .` 🆗 
- minor feedback about login page: if you don't have an uri but your auth rely on different admin db you can't login. So you need to rely on an uri in the form of `mongodb://root:passworkd@mongodbHost:27017/mydatabase?authSource=admin`
- CTRL + ENTER: work well thanks 👍 
- CTRL + SPACE to see hint (from your [diff](https://github.com/SamuelTS/MongoDB-PHP-GUI/commit/1e59e4e2481e01a9c67858e50add56c720c68a12)) seems not working for me.
- for your question about count IDK, maybe CTRL+* ?

**Comment by SamuelTS** [comment]
@creharmony 

> If I'am an user starting from scrach, I've to search mongo uri format, it could be great to have next to the URI input a way to set (ex. button or copy/paste) a default uri value

I found a compromise between "beginner-friendly" and "non-intrusive": show an example URI in placeholder.
![MongoDB PHP GUI - URI Placeholder Candidate](https://user-images.githubusercontent.com/36248671/139548691-3f6d2842-379f-4f49-827c-5252f5a211f8.jpg)

What do you think about?

**Comment by creharmony** [comment]
I like it 👍  😄

**Comment by SamuelTS** [comment]
@creharmony Since [v1.2.5](https://github.com/SamuelTS/MongoDB-PHP-GUI/releases/tag/v1.2.5), <kbd>Ctrl + *</kbd> triggers a "Count" action. BTW, MongoDB PHP GUI supports now regular expressions 😃

**Comment by creharmony** [comment]
Amazing : count/find works well ; thanks @SamuelTS for your work 👍 
I close this issue as all is done :)
