### ISSUE TITLE
Access through a reverse proxy

### ISSUE THREAD

**Issue by tonkolviktor** [SamuelTS/MongoDB-PHP-GUI#18]
Hello @SamuelTS,

First of all thanks for your work and for sharing it!

I'm trying to make the UI run, I have the requirement that it has to run behind a reverse proxy. For that I need two things:
- (1) freely configurable context prefix, eg.: http://localhost:5000/<context>/index
- (2a) any redirect to respect a REQUEST_URI, like: https://github.com/SamuelTS/MongoDB-PHP-GUI/blob/master/index.php#L66
- (2b) or make it possible to configure, like: https://docs.phpmyadmin.net/en/latest/config.html#cfg_PmaAbsoluteUri

(1) I could solve via a special docker setup hack [hack 1]. Albeit it would be certainly nicer to have an environment variable like: `docker run -p 5000:5000 samueltallet/mongodb-php-gui. -e CONTEXT='/my/base/url'`   or like 2b:
`docker run -p 5000:5000 samueltallet/mongodb-php-gui. -e ABS_URI='https://host.com/my/base/url'`

(2) My big problem is the login redirect as can be seen here:
![image](https://user-images.githubusercontent.com/4534324/123477376-3f93ea80-d5fe-11eb-9a06-43dfd8a204db.png)

It's just not good (for this setup).

I'm wondering if you would feel comfortable having 2a or rather 2b implemented in the codebase.

Thanks for your answer in advance.

Regards,
Viktor

[hack 1]
```
FROM php:7.4-cli-alpine

WORKDIR /opt/

RUN apk update && apk add --no-cache --virtual .build-deps autoconf build-base openssl-dev curl \
  && pecl install mongodb-1.8.2 && docker-php-ext-enable mongodb \
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
  && apk del .build-deps \
  && apk add --no-cache openjdk8-jre git

RUN git clone https://github.com/SamuelTS/MongoDB-PHP-GUI \
  && mkdir -p /opt/mongodb-php-gui/api/mongo-ui/ \
  && mv MongoDB-PHP-GUI/* /opt/mongodb-php-gui/api/mongo-ui/

WORKDIR /opt/mongodb-php-gui/api/mongo-ui/

RUN composer install

WORKDIR /opt/mongodb-php-gui/
EXPOSE 5000

CMD ["php", "-S", "0.0.0.0:5000"]
```

**Comment by SamuelTS** [comment]
Hello @tonkolviktor,
Since this GUI can be installed in a subfolder, could a [MPG_SERVER_PATH](https://github.com/SamuelTS/MongoDB-PHP-GUI/blob/master/index.php#L47) environment variable be enough for your needs?

**Comment by tonkolviktor** [comment]
Hello Samuel,

Thanks for the quick response.
Yes, that would be very helpful.
I do not have a good overview, but what is crucial is that the controller
redirect [1] should use this path for the internal redirects.

I'm happy to test and give feedback!

Thanks,
Viktor

[1]
https://github.com/SamuelTS/MongoDB-PHP-GUI/blob/master/src/Controllers/Controller.php#L17


Samuel Tallet ***@***.***> ezt írta (időpont: 2021. jún. 25.,
P, 23:16):

**Comment by SamuelTS** [comment]
> I do not have a good overview, but what is crucial is that the controller redirect should use this path for the internal redirects.

I agree.

**Comment by SamuelTS** [comment]
> I do not have a good overview, but what is crucial is that the controller redirect should use this path for the internal redirects.

`Controller::redirectTo()` method use `MPG_BASE_URL` constant which is based on `$_SERVER['REQUEST_URI']` variable. See [1]. So I don't understand why redirect fails. Could it be related to reverse proxy behavior?

[1] https://github.com/SamuelTS/MongoDB-PHP-GUI/blob/8ebe226905bbc5fb2d436ef398d6310b8dcd505f/index.php#L38-L40

**Comment by patrickdk77** [comment]
instead of using full paths and server names. just 7se realative url. dont use / anywhere at the start but just index.php or subdirectory names. if i find time ill look at coding a pr

**Comment by tonkolviktor** [comment]
I've done some testing. I've realized that the problem is not the context, but the HTTP_HOST.

When this parameter is missing from the ngnix reverse_proxy then the host is the local hostname not the reverse_proxy host name:
`proxy_set_header Host $http_host;`

Since in our environment pushing through a change like that is time consuming, I've did a workaround, which is not the nicest, but works :)
https://github.com/tonkolviktor/MongoDB-PHP-GUI/commit/af4e43761bfeb4d485f84b99f5040b87edf21c37

For the main product probably @patrickdk77's point is the best.

**Comment by SamuelTS** [comment]
@tonkolviktor You don't need to move files to `api/mongo-ui` folder anymore?

Could you please do a dirty test?
Replace this line:
```php
define('MPG_BASE_URL', $baseUrl);
```
by this line:
```php
define('MPG_BASE_URL', $serverPath);
```
Maybe we can omit the host and use `MPG_SERVER_PATH` instead of `MPG_BASE_URL` everywhere in code.

PS: I think it's safer to keep absolute paths.

**Comment by tonkolviktor** [comment]
@SamuelTS thanks I did.
Hm, at least the static files I still have to move, right? 
Maybe they need an extra route or something, but for me they fail:

```
HTML:
<script src="/api/mongo-ui/static/js/mpg.login.js"></script>
Log:
GET /api/mongo-ui/static/js/mpg.login.js - No such file or directory
```

**Comment by tonkolviktor** [comment]
Additionally I'm getting now a session problems, but this could be because one of my changes.

![image](https://user-images.githubusercontent.com/4534324/123541751-6a895600-d746-11eb-99c4-36ec6ed4884e.png)

PHPSESSID cookie is set and sent.

**Comment by SamuelTS** [comment]
> Hm, at least the static files I still have to move, right?

Yes. But it wasn't required previously? I'm lost 😆

**Comment by SamuelTS** [comment]
> Additionally I'm getting now a session problems, but this could be because one of my changes.

You should not debug with `print` [1]. This could cause issues. I think `error_log` is a better option.

[1] https://github.com/tonkolviktor/MongoDB-PHP-GUI/blob/7eaf05b551adc1883275c92480c92c21e341388a/src/Controllers/LoginController.php#L72

**Comment by SamuelTS** [comment]
@tonkolviktor I've released a version. Routing code is cleaner. This should not resolve your issue, but I encourage you to upgrade anyway.

**Comment by tonkolviktor** [comment]
@SamuelTS thanks!
A summary from my side is that the reverse proxy setup works.

I cannot fix the session problem that I'm having, which means unfortunately I cannot continue. However that must be something in my environment.

Thanks for the quick reply and action to make the reverse proxy work, hopefully it will be useful for someone else. From my side feel free to close the issue.

ps.: I wanted to clear one point before a deployment in a separate issue, but unfortunately that will not be relevant for me anymore. Still here it is: I could not find License information only [1], I would not know how to understand this. It would be nice to clarify what can be done with your code, like: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository

[1]
```
Copyright
© 2021 Samuel Tallet
```

**Comment by SamuelTS** [comment]
@tonkolviktor You're welcome. This project is licensed under [GPL v3](https://github.com/SamuelTS/MongoDB-PHP-GUI/blob/master/docs/LICENSE).
