### ISSUE TITLE
Can't insert exported data

### ISSUE THREAD

**Issue by Delimer** [SamuelTS/MongoDB-PHP-GUI#2]
In base one document
`array[1]
0{5}
_id{1}
  $oid:5f325f98114bec5750892193
email:delimer@gmail.com
emailVerified{1}
  $date{1}
    $numberLong:1597141066973
createdAt{1}
  $date{1}
    $numberLong:1597136792802
updatedAt{1}
  $date{1}
    $numberLong:1597141066984`

exporter
`[
    {
        "_id": {
            "$oid": "5f325f98114bec5750892193"
        },
        "email": "delimer@gmail.com",
        "emailVerified": {
            "$date": {
                "$numberLong": "1597141066973"
            }
        },
        "createdAt": {
            "$date": {
                "$numberLong": "1597136792802"
            }
        },
        "updatedAt": {
            "$date": {
                "$numberLong": "1597141066984"
            }
        }
    }
]`

when try insert get error 
Error: invalid document for insert: keys cannot begin with "$": "$date"

**Comment by SamuelTS** [comment]
Thanks @Delimer. I'll try to fix that.

**Comment by SamuelTS** [comment]
Since v1.0.3 of MongoDB PHP GUI, insertion of exported data is possible (but keep in mind that for now only one document at once can be inserted).  Please upgrade your version, then if you still experience any problem: feel free to reopen an issue.
