### ISSUE TITLE
Unsorted collection list

### ISSUE THREAD

**Issue by itschrono** [SamuelTS/MongoDB-PHP-GUI#7]
Hello I don't know if this is intended but when I select a database the list of collections is all mangled;
![image](https://user-images.githubusercontent.com/25153662/98923121-88fe5200-24d3-11eb-8986-96040103c310.png)

**Comment by SamuelTS** [comment]
Hello. Did you mean collections are not sorted alphabetically?

**Comment by itschrono** [comment]
> Hello. Did you mean collections are not sorted alphabetically?

Yes

**Comment by SamuelTS** [comment]
Since 1.1.0 version, databases and collections are sorted alphabetically. If you use Docker: please rebuild...

**Comment by itschrono** [comment]
> Since 1.1.0 version, databases and collections are sorted alphabetically. If you use Docker: please rebuild...

Awesome, thanks a lot 👍
