### ISSUE TITLE
[Docker] connection refused calling ismaster on '127.0.0.1:27017'

### ISSUE THREAD

**Issue by amrithadevadiga22** [SamuelTS/MongoDB-PHP-GUI#8]
I have followed these steps 

Docker (PHP built-in server)
Clone current repository.
Run once docker build -t mongodb-php-gui . at project's root directory.
Run docker run -it -p 5000:5000 mongodb-php-gui at project's root directory.
Open your browser at this address: http://127.0.0.1:5000/ to access GUI.

i am able access the UI but how to login ? what will be the credentials

**Comment by itschrono** [comment]
Hello, if you have a mongo container running you should use his name as host. The other are from the user(s) you created with init script or env variable. If you have only an "admin" user you should omit "Database" so you have access to your others databases.

**Comment by amrithadevadiga22** [comment]
HI, i tried to login via admin and gave connection as Host=127.0.0.1 and port=27017 , got error 
{
    "error": {
        "code": 13053,
        "message": "No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on '127.0.0.1:27017']"
    }
}

note : i checked in host machine that mongo db active and running ..please suggest me what i can do for this..
here i don't have mongo container , i have configured mongo db in dedicated host

**Comment by SamuelTS** [comment]
Hello. If your MongoDB host is accessible from Internet: use its IP address as host. Else: use 172.17.0.1 as host. Let me know if it works...

**Comment by amrithadevadiga22** [comment]
Hi, yes it worked for login, steps i followed like
created a user in mongo cli
and used same user credential and database name in login page with host 172.17.0.1 and port 27017.

but if i try to add user from ui for that DB it is giving me same error " message": "No suitable servers found (serverSelectionTryOnce set): [connection refused calling ismaster on '127.0.0.1:27017']"" please find attachment

and one thing with out giving DB name i am not able to login..so how to login as a admin ? any suggestion for this ?

**Comment by SamuelTS** [comment]
So when you try to add an user from UI, there's an error? Can you please attach a screenshot?

**Comment by amrithadevadiga22** [comment]
![Screenshot from 2020-11-18 11-10-06](https://user-images.githubusercontent.com/66819076/99489903-c7da4f00-298e-11eb-8398-e166ac53e956.png)
please find screenshot

after adding query it is not giving result also no error..
![Screenshot from 2020-11-18 11-08-16](https://user-images.githubusercontent.com/66819076/99489972-eb9d9500-298e-11eb-8621-5405240a12bd.png)

**Comment by SamuelTS** [comment]
@amrithadevadiga22 Hi. Thanks for the screenshots. To bypass the error "The SCRAM_SHA_256 authentication mechanism requires libmongoc built with ENABLE_SSL", follow these steps:

1. Replace _Dockerfile_ at project's root directory with this one:

```
FROM php:7.4-cli-alpine
RUN apk update && apk upgrade

# Clone project repository.
RUN apk add --no-cache git
WORKDIR /opt/mongodb-php-gui
RUN git clone https://github.com/SamuelTS/MongoDB-PHP-GUI.git .

# Enable MongoDB PHP ext.
RUN apk add --no-cache autoconf build-base curl-dev openssl-dev
RUN pecl install mongodb-1.8.2 && docker-php-ext-enable mongodb

# Install PHP dependencies.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install

# Start PHP built-in server.
EXPOSE 5000
CMD ["php", "-S", "0.0.0.0:5000"]
```
2. Run **again** `docker build -t mongodb-php-gui .` at project's root directory.
3. Run `docker run -it -p 5000:5000 mongodb-php-gui` at project's root directory.
4. Open your browser at this address: http://127.0.0.1:5000/ to access GUI.

Then, about querying, you don't need to write full command `db.mycol.find().pretty()`. Just write for example `{ "_id": 1 }`.

**Comment by amrithadevadiga22** [comment]
@SamuelTS Hi, Thanks for the reply..
i want to know ,what should be user role for a database to perform any operation ..i was getting authentication error for a user with the role "userAdmin" with user name "employee", for db "employee"

and one more thing like i tried some basic mongo db query commands
eg: db.COLLECTIONNAME.findOne()
db.mycol.find({ $and: [ {<key1>:<value1>}, { <key2>:<value2>} ] })
db.mycol.find().pretty()  etc..

non of the query giving output..as you gave example above like "{ "_id": 1 }", i didn't get how it actually working..and if i want to query the database with some condition how can i write a query !!

**Comment by SamuelTS** [comment]
@amrithadevadiga22 Hello.

I suggest you to drop then re-create user named "employee" for db "employee" with role [readWrite](https://docs.mongodb.com/manual/reference/built-in-roles/#readWrite).

You can query database using `{}` syntax. Input only value passed normally to `.find()`. Example:

![Query](https://raw.githubusercontent.com/SamuelTS/MongoDB-PHP-GUI/master/docs/screenshots/mpg-query-database.png)
