### ISSUE TITLE
Login fields configurable via env vars

### ISSUE THREAD

**Issue by cbakersdl** [SamuelTS/MongoDB-PHP-GUI#9]
For automated deployments it is desirable to pre-populate the login fields for user, host, port, database so these do not have to be looked up by the operator every time they need to login.

**Comment by SamuelTS** [comment]
Thanks for the idea!

**Comment by SamuelTS** [comment]
Thanks for idea. But I think it's dangerous to pre-populate the login fields via env vars, because if GUI URL is exposed at a moment, an attacker could take advantage of these. Using [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) may be more secure...

**Comment by pampatzoglou** [comment]
being able to set up any app through the usage of environmental variables is the standard way to do so.  This is in accordance with the 12-factor app guidelines as well as how most if not all cloud-native apps operate. I would love to see this in this project. As for the pre-populate part, this can be mitigated in multiple ways. For example, perform the auto-connect only if all the required variables are set (user, password, db, host, port).
